<?php

namespace src\Modules\Category\Domain\Entity;

use src\Core\Domain\Entities\AbstractAttributesEntity;
use src\Core\Domain\Entities\EntityInterface;

class CategoryItem extends AbstractAttributesEntity implements EntityInterface
{
    public CONST TABLE_NAME = "category_item";

    public $id;
    public $item_name;
    public $id_category;

    public function getTableName()
    {
        return self::TABLE_NAME;
    }

    public function getAttributes(): array
    {
        return parent::getAttributes(); // TODO: Change the autogenerated stub
    }
}