<?php

namespace src\Modules\Category\Domain\Entity;

use src\Core\Domain\Entities\AbstractAttributesEntity;
use src\Core\Domain\Entities\EntityInterface;

class CategoryItem extends AbstractAttributesEntity implements EntityInterface
{
    public $id;
    public $item_name;
    public $id_category;

    public static function getTableName()
    {
        return "category_item";
    }

    public function getAttributes(): array
    {
        return parent::getAttributes(); // TODO: Change the autogenerated stub
    }
}