<?php

namespace src\Modules\SysQuery\Domain\Entity;

use src\Core\Domain\Entities\AbstractAttributesEntity;
use src\Core\Domain\Entities\EntityInterface;

class SysQuery extends AbstractAttributesEntity implements EntityInterface
{
    public $id;
    public $sql_script;

    public static function getTableName()
    {
        return "query";
    }

    public function getAttributes(): array
    {
        return parent::getAttributes(); // TODO: Change the autogenerated stub
    }
}